---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    spruce_bin_path: "/usr/local/bin"
    spruce_version: "v1.30.2"
  tasks:
    - name: Ensure Spruce is installed
      ansible.builtin.stat:
        path: "{{ spruce_bin_path }}/spruce"
      register: this_stat

    - name: Get version from Spruce
      ansible.builtin.command: "{{ spruce_bin_path }}/spruce --version"
      register: this_exec

    - name: Assert binary exists
      ansible.builtin.assert:
        that:
          - this_stat.stat.exists

    - name: Assert version is correct
      ansible.builtin.assert:
        that:
          - spruce_version in this_exec.stdout
